import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowClockwise, CheckCircle, Clock, Info, Spinner, Warning, X } from '@phosphor-icons/react';
import { api } from '../api.js';
import '../styles/live-product.css';

const STATUS = { OPEN: ['Open now', 'var(--green)'], UPCOMING: ['Upcoming', 'var(--accent)'], CLOSED: ['Closed', 'var(--amber)'], LISTED: ['Listed', 'var(--text-2)'] };
const DECISION = { APPLY: ['var(--green)', 'var(--green-bg)'], WATCH: ['var(--amber)', 'var(--amber-bg)'], SKIP: ['var(--red)', 'var(--red-bg)'] };

const fmt = (v, n = 1) => v == null ? 'Unavailable' : typeof v === 'number' ? v.toFixed(n) : String(v);
const dateLabel = v => v ? new Date(`${v}T00:00:00`).toLocaleDateString('en-IN', { day: 'numeric', month: 'short' }) : 'Unavailable';
const timeLabel = v => v ? new Date(v).toLocaleString('en-IN', { day: 'numeric', month: 'short', hour: '2-digit', minute: '2-digit' }) : 'Unavailable';

function Status({ value }) { const item = STATUS[value] || ['Date unavailable', 'var(--text-2)']; return <span className="lp-status" style={{ color: item[1] }}>{item[0]}</span>; }
function Decision({ value }) { const item = DECISION[value] || ['var(--text-2)', 'var(--bg-3)']; return <span className="lp-decision" style={{ color: item[0], background: item[1] }}>{value || 'Unavailable'}</span>; }
function Quality({ value }) { const Icon = value === 'FULL' ? CheckCircle : Warning; return <span className="lp-quality"><Icon size={13} weight="fill" /> {value || 'Unavailable'}</span>; }
function Metric({ label, value, suffix = '' }) { return <div className="lp-metric"><span>{label}</span><strong>{value == null ? 'Unavailable' : `${fmt(value)}${suffix}`}</strong></div>; }

function IpoCard({ ipo, onOpen }) {
  const drivers = (ipo.drivers || []).slice(0, 2).map(x => x.replaceAll('_', ' '));
  return <button className={`lp-card lp-card-${(ipo.status || 'unknown').toLowerCase()}`} onClick={() => onOpen(ipo)}>
    <div className="lp-card-top"><div><h3>{ipo.company_name}</h3><p>{ipo.nse_symbol || 'Mainboard IPO'}</p></div><div className="lp-card-badges"><Status value={ipo.status} /><Decision value={ipo.recommendation} /></div></div>
    <div className="lp-terms"><div><span>Price</span><strong>{ipo.price_band_low != null && ipo.price_band_high != null ? `₹${ipo.price_band_low} to ₹${ipo.price_band_high}` : ipo.issue_price != null ? `₹${ipo.issue_price}` : 'Unavailable'}</strong></div><div><span>Window</span><strong>{dateLabel(ipo.open_date)} to {dateLabel(ipo.close_date)}</strong></div><div><span>Market</span><strong>{ipo.market_regime || 'Unavailable'}</strong></div></div>
    <div className="lp-metrics"><Metric label="Retail" value={ipo.subscription_retail_x} suffix="x" /><Metric label="NII" value={ipo.subscription_nii_x} suffix="x" /><Metric label="QIB" value={ipo.subscription_qib_x} suffix="x" /><Metric label="Total" value={ipo.subscription_total_x} suffix="x" /></div>
    <div className="lp-card-bottom"><span>{drivers.length ? drivers.join(' · ') : 'Decision evidence unavailable'}</span><small><Quality value={ipo.data_quality} /> {timeLabel(ipo.observed_at)}</small></div>
  </button>;
}

function Detail({ ipo, onClose }) {
  const [analysis, setAnalysis] = useState(null); const [loading, setLoading] = useState(true);
  useEffect(() => { let live = true; Promise.all([api.liveIpoAnalysis(ipo.ipo_id), api.liveSnapshots(ipo.ipo_id, 'subscription_total_x').catch(() => null)]).then(([a, history]) => { if (live) { setAnalysis({ ...a, history }); setLoading(false); } }).catch(() => live && setLoading(false)); return () => { live = false; }; }, [ipo.ipo_id]);
  return <div className="lp-overlay" onClick={onClose}><aside className="lp-detail" onClick={e => e.stopPropagation()}><button className="lp-close" onClick={onClose} aria-label="Close"><X size={20} /></button>{loading ? <div className="lp-loading"><Spinner size={26} /></div> : analysis ? <>
    <div className="lp-detail-kicker"><Status value={analysis.status} /> <span>{analysis.source}</span></div><h2>{analysis.company_name}</h2><p className="lp-detail-sub">{analysis.nse_symbol || 'Mainboard IPO'} · observed {timeLabel(analysis.observed_at)}</p>
    <div className="lp-decision-panel"><div><small>RULE_V1 DECISION</small><Decision value={analysis.recommendation} /></div><strong>{analysis.p_positive == null ? 'Unavailable' : `${Math.round(analysis.p_positive * 100)}%`}<span>positive listing estimate</span></strong></div>
    <section className="lp-detail-section"><h3>Why</h3><div className="lp-drivers">{(analysis.drivers || []).map(x => <span key={x}>{x.replaceAll('_', ' ')}</span>)}</div>{(analysis.reason_lines || []).map((x, i) => <p className="lp-reason" key={i}>{x}</p>)}</section>
    <div className="lp-detail-grid"><section className="lp-detail-section"><h3>Subscription</h3><Metric label="Retail" value={analysis.subscription_retail_x} suffix="x" /><Metric label="NII" value={analysis.subscription_nii_x} suffix="x" /><Metric label="QIB" value={analysis.subscription_qib_x} suffix="x" /><Metric label="Total" value={analysis.subscription_total_x} suffix="x" /></section><section className="lp-detail-section"><h3>Market</h3><Metric label="Regime" value={analysis.features_snapshot?.market_regime} /><Metric label="Nifty 5D" value={analysis.features_snapshot?.market_nifty_return_5d == null ? null : analysis.features_snapshot.market_nifty_return_5d * 100} suffix="%" /><Metric label="Nifty 20D" value={analysis.features_snapshot?.market_nifty_return_20d == null ? null : analysis.features_snapshot.market_nifty_return_20d * 100} suffix="%" /><Metric label="India VIX" value={analysis.features_snapshot?.market_india_vix_close} /></section></div>
    <div className="lp-detail-grid"><section className="lp-detail-section"><h3>Issue</h3><Metric label="Issue price" value={analysis.issue_price} suffix=" ₹" /><Metric label="Lot size" value={analysis.lot_size} /><Metric label="Issue size" value={analysis.issue_size_cr} suffix=" Cr" /></section><section className="lp-detail-section"><h3>Data quality</h3><Quality value={analysis.data_quality} /><p className="lp-muted">{analysis.confidence}<br />Retrieved {timeLabel(analysis.retrieved_at)}<br />Decision {timeLabel(analysis.decision_at)}<br />GMP {analysis.gmp_inr == null ? 'Unavailable' : `₹${analysis.gmp_inr}`}</p></section></div>
    {analysis.missing_fields?.length > 0 && <div className="lp-warning"><Info size={15} /> Missing: {analysis.missing_fields.join(', ')}</div>}{analysis.history?.observations?.length > 0 && <section className="lp-detail-section"><h3>Subscription history</h3>{analysis.history.observations.slice(-6).map((x, i) => <div className="lp-snapshot" key={i}><span>{timeLabel(x.observed_at)}</span><strong>{x.value == null ? 'Unavailable' : `${x.value}x`}</strong></div>)}</section>}
  </> : <p className="lp-muted">Analysis unavailable.</p>}</aside></div>;
}

export default function LiveProductPage() {
  const [data, setData] = useState(null); const [filter, setFilter] = useState(''); const [selected, setSelected] = useState(null); const [loading, setLoading] = useState(true); const [refreshing, setRefreshing] = useState(false); const [error, setError] = useState(null);
  const load = useCallback(async () => { try { setError(null); setData(await api.liveIpos(filter || undefined)); } catch (e) { setError(e.message); } finally { setLoading(false); } }, [filter]);
  useEffect(() => { load(); }, [load]);
  const refresh = async () => { setRefreshing(true); try { await api.triggerRefresh(); await new Promise(r => setTimeout(r, 3000)); await load(); } catch (e) { setError(e.message); } finally { setRefreshing(false); } };
  const ipos = data?.ipos || []; const open = useMemo(() => ipos.filter(x => x.status === 'OPEN'), [ipos]); const upcoming = useMemo(() => ipos.filter(x => x.status === 'UPCOMING'), [ipos]); const closed = useMemo(() => ipos.filter(x => x.status === 'CLOSED'), [ipos]); const listed = useMemo(() => ipos.filter(x => x.status === 'LISTED'), [ipos]);
  const sections = filter ? [{ title: STATUS[filter]?.[0] || filter, items: ipos }] : [{ title: 'Open now', items: open }, { title: 'Upcoming', items: upcoming }, { title: 'Recently closed', items: closed }, { title: 'Listed', items: listed.slice(0, 12) }];
  return <div className="live-product">{selected && <Detail ipo={selected} onClose={() => setSelected(null)} />}<header className="lp-header"><div><span className="lp-eyebrow">IPO TERMINAL · DECISION DESK</span><h1>Live IPOs</h1><p>Which issues deserve attention today?</p><small><i /> {data?.last_refreshed ? `Refreshed ${timeLabel(data.last_refreshed)}` : 'Waiting for live data'} · Chittorgarh and optional InvestorGain</small></div><button className="lp-refresh" onClick={refresh} disabled={refreshing}><ArrowClockwise size={16} className={refreshing ? 'lp-spin' : ''} /> {refreshing ? 'Refreshing' : 'Refresh data'}</button></header>
    <div className="lp-summary"><div><strong>{open.length}</strong><span>Open now</span></div><div><strong>{upcoming.length}</strong><span>Upcoming</span></div><div><strong>{closed.length}</strong><span>Closed</span></div><div><strong>{listed.length}</strong><span>Listed</span></div></div><nav className="lp-tabs">{['', 'OPEN', 'UPCOMING', 'CLOSED', 'LISTED'].map(x => <button className={filter === x ? 'active' : ''} key={x || 'ALL'} onClick={() => setFilter(x)}>{x || 'ALL'} {x && <span>{({ OPEN: open, UPCOMING: upcoming, CLOSED: closed, LISTED: listed })[x].length}</span>}</button>)}</nav>
    {loading ? <div className="lp-empty"><Spinner size={28} className="lp-spin" /><p>Loading current IPO data</p></div> : error ? <div className="lp-empty lp-error"><Warning size={28} /><h2>Live data is unavailable</h2><p>{error}</p><button className="lp-refresh" onClick={load}>Try again</button></div> : !ipos.length ? <div className="lp-empty"><Clock size={28} /><h2>{filter ? `No IPOs are ${STATUS[filter]?.[0].toLowerCase()}` : 'No live IPO data yet'}</h2><p>Refresh the source to check the latest issue calendar.</p></div> : <main className="lp-groups">{sections.filter(x => x.items.length).map(section => <section key={section.title}><div className="lp-group-title"><h2>{section.title}</h2><span>{section.items.length} IPO{section.items.length === 1 ? '' : 's'}</span></div><div className="lp-grid">{section.items.map(ipo => <IpoCard key={ipo.ipo_id} ipo={ipo} onOpen={setSelected} />)}</div></section>)}</main>}
    <footer className="lp-footer"><Info size={14} /> RULE_V1 is a deterministic estimate, not a validated prediction. Missing values stay unavailable. GMP is informational and excluded from the strategy.</footer></div>;
}
